province_codes = {
    "00": "Desconocida",
    "23": "La Habana",
    "25": "Matanzas",
    "27": "Cienfuegos",
    "28": "Sancti Spíritus",
    "31": "Las Tunas",
    "32": "Holguín",
    "33": "Granma",
    "34": "Santiago de Cuba",
    "40.01": "Isla de la Juventud",
    "30": "Camagüey",
    "29": "Ciego de Ávila",
    "26": "Villa Clara",
    "35": "Guantánamo",
    "21": "Pinar del Río",
    "22": "Artemisa",
    "24": "Mayabeque",
}

province_abbrs = {
    "unk": "Desconocida",
    "lha": "La Habana",
    "mat": "Matanzas",
    "cfg": "Cienfuegos",
    "ssp": "Sancti Spíritus",
    "ltu": "Las Tunas",
    "hol": "Holguín",
    "gra": "Granma",
    "stg": "Santiago de Cuba",
    "ijv": "Isla de la Juventud",
    "cam": "Camagüey",
    "cav": "Ciego de Ávila",
    "vcl": "Villa Clara",
    "gtm": "Guantánamo",
    "pri": "Pinar del Río",
    "art": "Artemisa",
    "may": "Mayabeque",
}
