countries = {
    'bd': 'Bangladesh',
    'be': 'Bélgica',
    'bf': 'Burkina Faso',
    'bg': 'Bulgaria',
    'ba': 'Bosnia y Herzegovina',
    'bb': 'Barbados',
    'wf': 'Wallis y Futuna',
    'bl': 'San Bartolomé',
    'bm': 'Islas Bermudas',
    'bn': 'Brunei',
    'bo': 'Bolivia',
    'bh': 'Bahrein',
    'bi': 'Burundi',
    'bj': 'Benin',
    'bt': 'Bután',
    'jm': 'Jamaica',
    'bv': 'Isla Bouvet',
    'bw': 'Botsuana',
    'ws': 'Samoa',
    'bq': 'Bonaire, San Eustaquio y Saba',
    'br': 'Brasil',
    'bs': 'Bahamas',
    'je': 'Jersey',
    'by': 'Bielorrusia',
    'bz': 'Belice',
    'ru': 'Rusia',
    'rw': 'Ruanda',
    'rs': 'Serbia',
    'tl': 'Timor Oriental',
    're': 'Reunión',
    'tm': 'Turkmenistán',
    'tj': 'Tayikistán',
    'ro': 'Rumania',
    'tk': 'Tokelau',
    'gw': 'Guinea-Bissau',
    'gu': 'Guam',
    'gt': 'Guatemala',
    'gs': 'Georgia del Sur y las Islas Sandwich del Sur',
    'gr': 'Grecia',
    'gq': 'Guinea Ecuatorial',
    'gp': 'Guadalupe',
    'jp': 'Japón',
    'gy': 'Guayana',
    'gg': 'Guernsey',
    'gf': 'Guayana Francesa',
    'ge': 'Georgia',
    'gd': 'Granada',
    'gb': 'Reino Unido',
    'ga': 'Gabón',
    'sv': 'El Salvador',
    'gn': 'Guinea',
    'gm': 'Gambia',
    'gl': 'Groenlandia',
    'gi': 'Gibraltar',
    'gh': 'Ghana',
    'om': 'Omán',
    'tn': 'Túnez',
    'jo': 'Jordán',
    'hr': 'Croacia',
    'ht': 'Haití',
    'hu': 'Hungría',
    'hk': 'Hong Kong',
    'hn': 'Honduras',
    'hm': 'Islas Heard y McDonald',
    've': 'Venezuela',
    'pr': 'Puerto Rico',
    'ps': 'Territorio Palestino',
    'pw': 'Palau',
    'pt': 'Portugal',
    'sj': 'Svalbard y Jan Mayen',
    'py': 'Paraguay',
    'iq': 'Irak',
    'pa': 'Panamá',
    'pf': 'Polinesia francés',
    'pg': 'Papúa Nueva Guinea',
    'pe': 'Perú',
    'pk': 'Pakistán',
    'ph': 'Filipinas',
    'pn': 'Pitcairn',
    'pl': 'Polonia',
    'pm': 'San Pedro y Miquelón',
    'zm': 'Zambia',
    'eh': 'Sahara Occidental',
    'ee': 'Estonia',
    'eg': 'Egipto',
    'za': 'Sudáfrica',
    'ec': 'Ecuador',
    'it': 'Italia',
    'vn': 'Vietnam',
    'sb': 'Islas Salomón',
    'et': 'Etiopía',
    'so': 'Somalia',
    'zw': 'Zimbabue',
    'sa': 'Arabia Saudita',
    'es': 'España',
    'er': 'Eritrea',
    'me': 'Montenegro',
    'md': 'Moldavia',
    'mg': 'Madagascar',
    'mf': 'San Martín',
    'ma': 'Marruecos',
    'mc': 'Mónaco',
    'uz': 'Uzbekistán',
    'mm': 'Myanmar',
    'ml': 'Mali',
    'mo': 'Macao',
    'mn': 'Mongolia',
    'mh': 'Islas Marshall',
    'mk': 'macedonia',
    'mu': 'Mauricio',
    'mt': 'Malta',
    'mw': 'Malawi',
    'mv': 'Maldivas',
    'mq': 'Martinica',
    'mp': 'Islas Marianas del Norte',
    'ms': 'Montserrat',
    'mr': 'Mauritania',
    'im': 'Isla del hombre',
    'ug': 'Uganda',
    'tz': 'Tanzania',
    'my': 'Malasia',
    'mx': 'Mexico',
    'il': 'Israel',
    'fr': 'Francia',
    'io': 'Territorio Británico del Océano Índico',
    'sh': 'Santa helena',
    'fi': 'Finlandia',
    'fj': 'Fiyi',
    'fk': 'Islas Malvinas',
    'fm': 'Micronesia',
    'fo': 'Islas Faroe',
    'ni': 'Nicaragua',
    'nl': 'Países Bajos',
    'no': 'Noruega',
    'na': 'Namibia',
    'vu': 'Vanuatu',
    'nc': 'Nueva Caledonia',
    'ne': 'Níger',
    'nf': 'Isla Norfolk',
    'ng': 'Nigeria',
    'nz': 'Nueva Zelanda',
    'np': 'Nepal',
    'nr': 'Nauru',
    'nu': 'Niue',
    'ck': 'Islas Cook',
    'xk': 'Kosovo',
    'ci': 'Costa de Marfil',
    'ch': 'Suiza',
    'co': 'Colombia',
    'cn': 'China',
    'cm': 'Camerún',
    'cl': 'Chile',
    'cc': 'Islas Cocos',
    'ca': 'Canadá',
    'cg': 'República del congo',
    'cf': 'República Centroafricana',
    'cd': 'República Democrática del Congo',
    'cz': 'Republica checa',
    'cy': 'Chipre',
    'cx': 'Isla de Navidad',
    'cr': 'Costa Rica',
    'cw': 'Curacao',
    'cv': 'Cabo Verde',
    'cu': 'Cuba',
    'sz': 'Swazilandia',
    'sy': 'Siria',
    'sx': 'Sint Maarten',
    'kg': 'Kirguistán',
    'ke': 'Kenia',
    'ss': 'Sudán del Sur',
    'sr': 'Surinam',
    'ki': 'Kiribati',
    'kh': 'Camboya',
    'kn': 'San Cristóbal y Nieves',
    'km': 'Comoras',
    'st': 'Santo Tomé y Príncipe',
    'sk': 'Eslovaquia',
    'kr': 'Corea del Sur',
    'si': 'Eslovenia',
    'kp': 'Corea del Norte',
    'kw': 'Kuwait',
    'sn': 'Senegal',
    'sm': 'San Marino',
    'sl': 'Sierra Leona',
    'sc': 'Seychelles',
    'kz': 'Kazajstán',
    'ky': 'Islas Caimán',
    'sg': 'Singapur',
    'se': 'Suecia',
    'sd': 'Sudán',
    'do': 'República Dominicana',
    'dm': 'Dominica',
    'dj': 'Djibouti',
    'dk': 'Dinamarca',
    'vg': 'Islas Vírgenes Británicas',
    'de': 'Alemania',
    'ye': 'Yemen',
    'dz': 'Argelia',
    'us': 'Estados Unidos',
    'uy': 'Uruguay',
    'yt': 'Mayotte',
    'um': 'Islas ultramarinas menores de Estados Unidos',
    'lb': 'Líbano',
    'lc': 'Santa Lucía',
    'la': 'Laos',
    'tv': 'Tuvalu',
    'tw': 'Taiwán',
    'tt': 'Trinidad y Tobago',
    'tr': 'Turquía',
    'lk': 'Sri Lanka',
    'li': 'Liechtenstein',
    'lv': 'Letonia',
    'to': 'Tonga',
    'lt': 'Lituania',
    'lu': 'Luxemburgo',
    'lr': 'Liberia',
    'ls': 'Lesoto',
    'th': 'Tailandia',
    'tf': 'Territorios Franceses del Sur',
    'tg': 'Ir',
    'td': 'Chad',
    'tc': 'Islas Turcas y Caicos',
    'ly': 'Libia',
    'va': 'Vaticano',
    'vc': 'San Vicente y las Granadinas',
    'ae': 'Emiratos Árabes Unidos',
    'ad': 'Andorra',
    'ag': 'Antigua y Barbuda',
    'af': 'Afganistán',
    'ai': 'Anguila',
    'vi': 'Islas Vírgenes de EE.UU',
    'is': 'Islandia',
    'ir': 'Corrí',
    'am': 'Armenia',
    'al': 'Albania',
    'ao': 'Angola',
    'aq': 'Antártida',
    'as': 'Samoa Americana',
    'ar': 'Argentina',
    'au': 'Australia',
    'at': 'Austria',
    'aw': 'Aruba',
    'in': 'India',
    'ax': 'Islas Aland',
    'az': 'Azerbaiyán',
    'ie': 'Irlanda',
    'id': 'Indonesia',
    'ua': 'Ucrania',
    'qa': 'Katar',
    'mz': 'Mozambique'
}

countries_codes = {
    "AFG": "Afghanistan",
    "ALB": "Albania",
    "DZA": "Algeria",
    "AND": "Andorra",
    "AGO": "Angola",
    "ATG": "Antigua and Barbuda",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BHS": "Bahamas",
    "BHR": "Bahrain",
    "BGD": "Bangladesh",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BEL": "Belgium",
    "BLZ": "Belize",
    "BTN": "Bhutan",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BRA": "Brazil",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "CPV": "Cabo Verde",
    "KHM": "Cambodia",
    "CMR": "Cameroon",
    "CAN": "Canada",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "CHL": "Chile",
    "CHN": "China",
    "COL": "Colombia",
    "CRI": "Costa Rica",
    "CIV": "Cote d'Ivoire",
    "HRV": "Croatia",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "DNK": "Denmark",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "SLV": "El Salvador",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FJI": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GAB": "Gabon",
    "GMB": "Gambia",
    "GEO": "Georgia",
    "DEU": "Germany",
    "GHA": "Ghana",
    "GRC": "Greece",
    "GRD": "Grenada",
    "GTM": "Guatemala",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "HND": "Honduras",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IND": "India",
    "IDN": "Indonesia",
    "IRQ": "Iraq",
    "IRL": "Ireland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JPN": "Japan",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KOR": "Korea, South",
    "KWT": "Kuwait",
    "KGZ": "Kyrgyzstan",
    "LAO": "Laos",
    "LVA": "Latvia",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MDG": "Madagascar",
    "MYS": "Malaysia",
    "MDV": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MRT": "Mauritania",
    "MUS": "Mauritius",
    "MDA": "Moldova",
    "MCO": "Monaco",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "NAM": "Namibia",
    "NPL": "Nepal",
    "NLD": "Netherlands",
    "NZL": "New Zealand",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "NOR": "Norway",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PRY": "Paraguay",
    "PER": "Peru",
    "PHL": "Philippines",
    "POL": "Poland",
    "PRT": "Portugal",
    "ROU": "Romania",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "KNA": "Saint Kitts and Nevis",
    "LCA": "Saint Lucia",
    "VCT": "Saint Vincent and the Grenadines",
    "SMR": "San Marino",
    "SAU": "Saudi Arabia",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SGP": "Singapore",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "ESP": "Spain",
    "LKA": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "SYR": "Syria",
    "TZA": "Tanzania",
    "THA": "Thailand",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "ARE": "United Arab Emirates",
    "GBR": "United Kingdom",
    "USA": "US",
    "URY": "Uruguay",
    "UZB": "Uzbekistan",
    "VEN": "Venezuela",
    "VNM": "Vietnam",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe"
}

countries_iso3Code = {
    "Afghanistan": "AFG",
    "Albania": "ALB",
    "Algeria": "DZA",
    "Andorra": "AND",
    "Angola": "AGO",
    "Antigua and Barbuda": "ATG",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Bahamas": "BHS",
    "Bahrain": "BHR",
    "Bangladesh": "BGD",
    "Barbados": "BRB",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Belize": "BLZ",
    "Bhutan": "BTN",
    "Bolivia": "BOL",
    "Bosnia and Herzegovina": "BIH",
    "Brazil": "BRA",
    "Bulgaria": "BGR",
    "Burkina Faso": "BFA",
    "Cabo Verde": "CPV",
    "Cambodia": "KHM",
    "Cameroon": "CMR",
    "Canada": "CAN",
    "Central African Republic": "CAF",
    "Chad": "TCD",
    "Chile": "CHL",
    "China": "CHN",
    "Colombia": "COL",
    "Costa Rica": "CRI",
    "Cote d'Ivoire": "CIV",
    "Croatia": "HRV",
    "Cuba": "CUB",
    "Cyprus": "CYP",
    "Denmark": "DNK",
    "Dominica": "DMA",
    "Dominican Republic": "DOM",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "El Salvador": "SLV",
    "Equatorial Guinea": "GNQ",
    "Eritrea": "ERI",
    "Estonia": "EST",
    "Ethiopia": "ETH",
    "Fiji": "FJI",
    "Finland": "FIN",
    "France": "FRA",
    "Gabon": "GAB",
    "Gambia": "GMB",
    "Georgia": "GEO",
    "Germany": "DEU",
    "Ghana": "GHA",
    "Greece": "GRC",
    "Grenada": "GRD",
    "Guatemala": "GTM",
    "Guinea": "GIN",
    "Guinea-Bissau": "GNB",
    "Guyana": "GUY",
    "Haiti": "HTI",
    "Honduras": "HND",
    "Hungary": "HUN",
    "Iceland": "ISL",
    "India": "IND",
    "Indonesia": "IDN",
    "Iraq": "IRQ",
    "Ireland": "IRL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Jordan": "JOR",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Korea, South": "KOR",
    "Kuwait": "KWT",
    "Kyrgyzstan": "KGZ",
    "Laos": "LAO",
    "Latvia": "LVA",
    "Lebanon": "LBN",
    "Liberia": "LBR",
    "Libya": "LBY",
    "Liechtenstein": "LIE",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Madagascar": "MDG",
    "Malaysia": "MYS",
    "Maldives": "MDV",
    "Mali": "MLI",
    "Malta": "MLT",
    "Mauritania": "MRT",
    "Mauritius": "MUS",
    "Moldova": "MDA",
    "Monaco": "MCO",
    "Mongolia": "MNG",
    "Montenegro": "MNE",
    "Morocco": "MAR",
    "Mozambique": "MOZ",
    "Namibia": "NAM",
    "Nepal": "NPL",
    "Netherlands": "NLD",
    "New Zealand": "NZL",
    "Nicaragua": "NIC",
    "Niger": "NER",
    "Nigeria": "NGA",
    "Norway": "NOR",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Papua New Guinea": "PNG",
    "Paraguay": "PRY",
    "Peru": "PER",
    "Philippines": "PHL",
    "Poland": "POL",
    "Portugal": "PRT",
    "Romania": "ROU",
    "Russia": "RUS",
    "Rwanda": "RWA",
    "Saint Kitts and Nevis": "KNA",
    "Saint Lucia": "LCA",
    "Saint Vincent and the Grenadines": "VCT",
    "San Marino": "SMR",
    "Saudi Arabia": "SAU",
    "Senegal": "SEN",
    "Serbia": "SRB",
    "Seychelles": "SYC",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Somalia": "SOM",
    "South Africa": "ZAF",
    "Spain": "ESP",
    "Sri Lanka": "LKA",
    "Sudan": "SDN",
    "Suriname": "SUR",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Syria": "SYR",
    "Tanzania": "TZA",
    "Thailand": "THA",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "United Arab Emirates": "ARE",
    "United Kingdom": "GBR",
    "US": "USA",
    "Uruguay": "URY",
    "Uzbekistan": "UZB",
    "Venezuela": "VEN",
    "Vietnam": "VNM",
    "Zambia": "ZMB",
    "Zimbabwe": "ZWE",
    "Benin": "BEN",
    "Brunei": "BRN",
    "Congo (Brazzaville)": "COG",
    "Congo (Kinshasa)": "COD",
    "Czechia": "CZE",
    "Djibouti": "DJI",
    "Eswatini": "SWZ",
    "Holy See": "VAT",
    "Iran": "IRN",
    "Mexico": "MEX",
    "North Macedonia": "MKD",
    "Qatar": "QAT",
    "Taiwan*": "TWN",
    "Togo": "TGO",
    "Timor-Leste": "TLS",
    "West Bank and Gaza": "PSE",
    "Kosovo": "RKS",
    "Burma": "MMR",
    "Botswana": "BWA",
    "Burundi": "BDI",
    "Sierra Leone": "SLE",
    "Malawi": "MWI",
    "South Sudan": "SSD",
    "Western Sahara": "ESH",
    "Sao Tome and Principe": "STP",
    "Yemen": "YEM",
}

trans_countries = {
    'Western Sahara': 'Sahara Occidental',
    'Sao Tome and Principe': 'Santo Tomé y Príncipe',
    'Yemen': 'Yemen',
    'South Sudan': 'Sudán del Sur',
    'Malawi': 'Malaui',
    'Sierra Leone': 'Sierra Leona',
    'Burundi': 'Burundi',
    'Botswana': 'Botsuana',
    'Vietnam': 'Vietnam',
    'Austria': 'Austria',
    'Cambodia': 'Camboya',
    'Kazakhstan': 'Kazajstán',
    "Cote d'Ivoire": 'Costa de Marfil',
    'Spain': 'España',
    'Serbia': 'Serbia',
    'Ethiopia': 'Etiopía',
    'Brazil': 'Brasil',
    'Pakistan': 'Pakistán',
    'Panama': 'Panamá',
    'Syria': 'Siria',
    'France': 'Francia',
    'Germany': 'Alemania',
    'Montenegro': 'Montenegro',
    'Switzerland': 'Suiza',
    'Paraguay': 'Paraguay',
    'Holy See': 'Santa Sede',
    'Nepal': 'Nepal',
    'Norway': 'Noruega',
    'Afghanistan': 'Afganistán',
    'Djibouti': 'Yitubi',
    'Ireland': 'Irlanda',
    'United Arab Emirates': 'Emiratos Árabes Unidos',
    'Israel': 'Israel',
    'Bulgaria': 'Bulgaria',
    'Korea, South': 'Corea del Sur',
    'Cyprus': 'Chipre',
    'Peru': 'Perú',
    'Azerbaijan': 'Azerbaiyán',
    'Philippines': 'Filipinas',
    'Bahamas': 'Bahamas',
    'India': 'India',
    'Canada': 'Canadá',
    'Rwanda': 'Ruanda',
    'Cuba': 'Cuba',
    'Thailand': 'Tailandia',
    'Brunei': 'Brunéi',
    'El Salvador': 'El Salvador',
    'North Macedonia': 'Macedonia del Norte',
    'Saint Vincent and the Grenadines': 'San Vicente y las Granadinas',
    'Jamaica': 'Jamaica',
    'Greece': 'Grecia',
    'Bolivia': 'Bolivia',
    'Dominica': 'Dominica',
    'Togo': 'Togo',
    'Mauritius': 'Mauricio',
    'Russia': 'Rusia',
    'Lebanon': 'Líbano',
    'Zimbabwe': 'Zimbabue',
    'Nigeria': 'Nigeria',
    'Finland': 'Finlandia',
    'Burma': 'Birmania',
    'Iraq': 'Irak',
    'United Kingdom': 'Reino Unido',
    'Tanzania': 'Tanzania',
    'Uruguay': 'Uruguay',
    'South Africa': 'Sudáfrica',
    'Somalia': 'Somalia',
    'Algeria': 'Argelia',
    'Benin': 'Benín',
    'Niger': 'Níger',
    'West Bank and Gaza': 'Cisjordania',
    'Uganda': 'Uganda',
    'San Marino': 'San Marino',
    'Liberia': 'Liberia',
    'Iran': 'Irán',
    'Mexico': 'México',
    'Honduras': 'Honduras',
    'Burkina Faso': 'Burkina Faso',
    'Australia': 'Australia',
    'Chile': 'Chile',
    'Haiti': 'Haití',
    'Turkey': 'Turquía',
    'Madagascar': 'Madagascar',
    'Saint Lucia': 'Santa Lucía',
    'Papua New Guinea': 'Papúa Nueva Guinea',
    'Central African Republic': 'República Centroafricana',
    'Eritrea': 'Eritrea',
    'Lithuania': 'Lituania',
    'Kyrgyzstan': 'Kirguistán',
    'Andorra': 'Andorra',
    'Laos': 'Laos',
    'Mali': 'Mali',
    'Guinea': 'Guinea',
    'Luxembourg': 'Luxemburgo',
    'Gambia': 'Gambia',
    'Mongolia': 'Mongolia',
    'Costa Rica': 'Costa Rica',
    'Trinidad and Tobago': 'Trinidad y Tobago',
    'Mauritania': 'Mauritania',
    'Antigua and Barbuda': 'Antigua y Barbuda',
    'Libya': 'Libia',
    'Zambia': 'Zambia',
    'Timor-Leste': 'Timor-Leste',
    'Guyana': 'Guayana',
    'Tunisia': 'Túnez',
    'Japan': 'Japón',
    'Liechtenstein': 'Liechtenstein',
    'Saint Kitts and Nevis': 'San Cristóbal y Nieves',
    'Senegal': 'Senegal',
    'Hungary': 'Hungría',
    'Moldova': 'Moldavia',
    'Qatar': 'Qatar',
    'US': 'Estados Unidos',
    'Belarus': 'Bielorrusia',
    'Chad': 'Chad',
    'Malaysia': 'Malasia',
    'Romania': 'Rumania',
    'Argentina': 'Argentina',
    'Belize': 'Belice',
    'Angola': 'Angola',
    'Sweden': 'Suecia',
    'China': 'China',
    'Jordan': 'Jordán',
    'Italy': 'Italia',
    'Latvia': 'Letonia',
    'Seychelles': 'Seychelles',
    'Ghana': 'Ghana',
    'Colombia': 'Colombia',
    'Albania': 'Albania',
    'Saudi Arabia': 'Arabia Saudita',
    'Estonia': 'Estonia',
    'Monaco': 'Mónaco',
    'Ukraine': 'Ucrania',
    'Uzbekistan': 'Uzbekistán',
    'Maldives': 'Maldivas',
    'Morocco': 'Marruecos',
    'Portugal': 'Portugal',
    'Kenya': 'Kenia',
    'Guatemala': 'Guatemala',
    'Gabon': 'Gabón',
    'Belgium': 'Bélgica',
    'Iceland': 'Islandia',
    'Cabo Verde': 'Cabo Verde',
    'Mozambique': 'Mozambique',
    'Indonesia': 'Indonesia',
    'Egypt': 'Egipto',
    'Taiwan*': 'Taiwán *',
    'Netherlands': 'Países Bajos',
    'Slovakia': 'Eslovaquia',
    'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
    'Cameroon': 'Camerún',
    'Venezuela': 'Venezuela',
    'Kuwait': 'Kuwait',
    'Malta': 'Malta',
    'Nicaragua': 'Nicaragua',
    'Congo (Kinshasa)': 'Congo (Kinshasa)',
    'Singapore': 'Singapur',
    'Bhutan': 'Bután',
    'Bangladesh': 'Bangladesh',
    'Ecuador': 'Ecuador',
    'Georgia': 'Georgia',
    'Namibia': 'Namibia',
    'Denmark': 'Dinamarca',
    'Poland': 'Polonia',
    'Suriname': 'Surinam',
    'Slovenia': 'Eslovenia',
    'Congo (Brazzaville)': 'Congo (Brazzaville)',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Dominican Republic': 'República Dominicana',
    'Grenada': 'Granada',
    'Barbados': 'Barbados',
    'New Zealand': 'Nueva Zelanda',
    'Eswatini': 'Eswatini',
    'Czechia': 'Chequia',
    'Kosovo': 'Kosovo',
    'Sudan': 'Sudán',
    'Armenia': 'Armenia',
    'Bahrain': 'Bahrein',
    'Sri Lanka': 'Sri Lanka',
    'Equatorial Guinea': 'Guinea Ecuatorial',
    'Croatia': 'Croacia',
    'Oman': 'Omán',
    'Fiji': 'Fiyi',
}
