countries = {
    "bd": "Bangladesh",
    "be": "Bélgica",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "ba": "Bosnia y Herzegovina",
    "bb": "Barbados",
    "wf": "Wallis y Futuna",
    "bl": "San Bartolomé",
    "bm": "Islas Bermudas",
    "bn": "Brunei",
    "bo": "Bolivia",
    "bh": "Bahrein",
    "bi": "Burundi",
    "bj": "Benin",
    "bt": "Bután",
    "jm": "Jamaica",
    "bv": "Isla Bouvet",
    "bw": "Botsuana",
    "ws": "Samoa",
    "bq": "Bonaire, San Eustaquio y Saba",
    "br": "Brasil",
    "bs": "Bahamas",
    "je": "Jersey",
    "by": "Bielorrusia",
    "bz": "Belice",
    "ru": "Rusia",
    "rw": "Ruanda",
    "rs": "Serbia",
    "tl": "Timor Oriental",
    "re": "Reunión",
    "tm": "Turkmenistán",
    "tj": "Tayikistán",
    "ro": "Rumania",
    "tk": "Tokelau",
    "gw": "Guinea-Bissau",
    "gu": "Guam",
    "gt": "Guatemala",
    "gs": "Georgia del Sur y las Islas Sandwich del Sur",
    "gr": "Grecia",
    "gq": "Guinea Ecuatorial",
    "gp": "Guadalupe",
    "jp": "Japón",
    "gy": "Guayana",
    "gg": "Guernsey",
    "gf": "Guayana Francesa",
    "ge": "Georgia",
    "gd": "Granada",
    "gb": "Reino Unido",
    "ga": "Gabón",
    "sv": "El Salvador",
    "gn": "Guinea",
    "gm": "Gambia",
    "gl": "Groenlandia",
    "gi": "Gibraltar",
    "gh": "Ghana",
    "om": "Omán",
    "tn": "Túnez",
    "jo": "Jordán",
    "hr": "Croacia",
    "ht": "Haití",
    "hu": "Hungría",
    "hk": "Hong Kong",
    "hn": "Honduras",
    "hm": "Islas Heard y McDonald",
    "ve": "Venezuela",
    "pr": "Puerto Rico",
    "ps": "Territorio Palestino",
    "pw": "Palau",
    "pt": "Portugal",
    "sj": "Svalbard y Jan Mayen",
    "py": "Paraguay",
    "iq": "Irak",
    "pa": "Panamá",
    "pf": "Polinesia francés",
    "pg": "Papúa Nueva Guinea",
    "pe": "Perú",
    "pk": "Pakistán",
    "ph": "Filipinas",
    "pn": "Pitcairn",
    "pl": "Polonia",
    "pm": "San Pedro y Miquelón",
    "zm": "Zambia",
    "eh": "Sahara Occidental",
    "ee": "Estonia",
    "eg": "Egipto",
    "za": "Sudáfrica",
    "ec": "Ecuador",
    "it": "Italia",
    "vn": "Vietnam",
    "sb": "Islas Salomón",
    "et": "Etiopía",
    "so": "Somalia",
    "zw": "Zimbabue",
    "sa": "Arabia Saudita",
    "es": "España",
    "er": "Eritrea",
    "me": "Montenegro",
    "md": "Moldavia",
    "mg": "Madagascar",
    "mf": "San Martín",
    "ma": "Marruecos",
    "mc": "Mónaco",
    "uz": "Uzbekistán",
    "mm": "Myanmar",
    "ml": "Mali",
    "mo": "Macao",
    "mn": "Mongolia",
    "mh": "Islas Marshall",
    "mk": "macedonia",
    "mu": "Mauricio",
    "mt": "Malta",
    "mw": "Malawi",
    "mv": "Maldivas",
    "mq": "Martinica",
    "mp": "Islas Marianas del Norte",
    "ms": "Montserrat",
    "mr": "Mauritania",
    "im": "Isla del hombre",
    "ug": "Uganda",
    "tz": "Tanzania",
    "my": "Malasia",
    "mx": "Mexico",
    "il": "Israel",
    "fr": "Francia",
    "io": "Territorio Británico del Océano Índico",
    "sh": "Santa helena",
    "fi": "Finlandia",
    "fj": "Fiyi",
    "fk": "Islas Malvinas",
    "fm": "Micronesia",
    "fo": "Islas Faroe",
    "ni": "Nicaragua",
    "nl": "Países Bajos",
    "no": "Noruega",
    "na": "Namibia",
    "vu": "Vanuatu",
    "nc": "Nueva Caledonia",
    "ne": "Níger",
    "nf": "Isla Norfolk",
    "ng": "Nigeria",
    "nz": "Nueva Zelanda",
    "np": "Nepal",
    "nr": "Nauru",
    "nu": "Niue",
    "ck": "Islas Cook",
    "xk": "Kosovo",
    "ci": "Costa de Marfil",
    "ch": "Suiza",
    "co": "Colombia",
    "cn": "China",
    "cm": "Camerún",
    "cl": "Chile",
    "cc": "Islas Cocos",
    "ca": "Canadá",
    "cg": "República del congo",
    "cf": "República Centroafricana",
    "cd": "República Democrática del Congo",
    "cz": "Republica checa",
    "cy": "Chipre",
    "cx": "Isla de Navidad",
    "cr": "Costa Rica",
    "cw": "Curacao",
    "cv": "Cabo Verde",
    "cu": "Cuba",
    "sz": "Swazilandia",
    "sy": "Siria",
    "sx": "Sint Maarten",
    "kg": "Kirguistán",
    "ke": "Kenia",
    "ss": "Sudán del Sur",
    "sr": "Surinam",
    "ki": "Kiribati",
    "kh": "Camboya",
    "kn": "San Cristóbal y Nieves",
    "km": "Comoras",
    "st": "Santo Tomé y Príncipe",
    "sk": "Eslovaquia",
    "kr": "Corea del Sur",
    "si": "Eslovenia",
    "kp": "Corea del Norte",
    "kw": "Kuwait",
    "sn": "Senegal",
    "sm": "San Marino",
    "sl": "Sierra Leona",
    "sc": "Seychelles",
    "kz": "Kazajstán",
    "ky": "Islas Caimán",
    "sg": "Singapur",
    "se": "Suecia",
    "sd": "Sudán",
    "do": "República Dominicana",
    "dm": "Dominica",
    "dj": "Djibouti",
    "dk": "Dinamarca",
    "vg": "Islas Vírgenes Británicas",
    "de": "Alemania",
    "ye": "Yemen",
    "dz": "Argelia",
    "us": "Estados Unidos",
    "uy": "Uruguay",
    "yt": "Mayotte",
    "um": "Islas ultramarinas menores de Estados Unidos",
    "lb": "Líbano",
    "lc": "Santa Lucía",
    "la": "Laos",
    "tv": "Tuvalu",
    "tw": "Taiwán",
    "tt": "Trinidad y Tobago",
    "tr": "Turquía",
    "lk": "Sri Lanka",
    "li": "Liechtenstein",
    "lv": "Letonia",
    "to": "Tonga",
    "lt": "Lituania",
    "lu": "Luxemburgo",
    "lr": "Liberia",
    "ls": "Lesoto",
    "th": "Tailandia",
    "tf": "Territorios Franceses del Sur",
    "tg": "Ir",
    "td": "Chad",
    "tc": "Islas Turcas y Caicos",
    "ly": "Libia",
    "va": "Vaticano",
    "vc": "San Vicente y las Granadinas",
    "ae": "Emiratos Árabes Unidos",
    "ad": "Andorra",
    "ag": "Antigua y Barbuda",
    "af": "Afganistán",
    "ai": "Anguila",
    "vi": "Islas Vírgenes de EE.UU",
    "is": "Islandia",
    "ir": "Corrí",
    "am": "Armenia",
    "al": "Albania",
    "ao": "Angola",
    "aq": "Antártida",
    "as": "Samoa Americana",
    "ar": "Argentina",
    "au": "Australia",
    "at": "Austria",
    "aw": "Aruba",
    "in": "India",
    "ax": "Islas Aland",
    "az": "Azerbaiyán",
    "ie": "Irlanda",
    "id": "Indonesia",
    "ua": "Ucrania",
    "qa": "Katar",
    "mz": "Mozambique"
}
